"""Pure identity and state types for linked Google recurring occurrences.

An occurrence is identified by the slot generated by the *original* local
series schedule.  Its current start may move on either side without changing
that identity:

``Task.series_uid + Task.occurrence_key``
    Stable Planner identity.

``recurringEventId + originalStartTime``
    Stable Google identity.

This module deliberately has no repositories, Qt objects, Google clients or
network access.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from datetime import date, datetime, time
from enum import Enum
from typing import Any, Mapping, Optional, Tuple
from zoneinfo import ZoneInfo

from planner_desktop.domain.recurrence import (
    SeriesSchedule,
    TaskSeries,
    occurrence_key as build_occurrence_key,
    resolve_wall_clock,
)
from planner_desktop.domain.task import utc_now


PLANNER_OCCURRENCE_SCHEMA_VERSION = "1"
PLANNER_OCCURRENCE_SERIES_UID_PROPERTY = "planner_series_uid"
PLANNER_OCCURRENCE_KEY_PROPERTY = "planner_occurrence_key"
PLANNER_OCCURRENCE_LINK_GENERATION_PROPERTY = "planner_link_generation"
PLANNER_OCCURRENCE_PAYLOAD_HASH_PROPERTY = "planner_occurrence_payload_hash"
PLANNER_OCCURRENCE_SCHEMA_VERSION_PROPERTY = "planner_occurrence_schema_version"


class OccurrenceSyncStatus(str, Enum):
    LOCAL_ONLY = "local_only"
    PENDING_UPDATE = "pending_update"
    SYNCED_EXCEPTION = "synced_exception"
    PENDING_CANCEL = "pending_cancel"
    CANCELLED = "cancelled"
    CONFLICT = "conflict"
    REMOTE_CHANGED = "remote_changed"
    REMOTE_CANCELLED = "remote_cancelled"
    TERMINAL_ERROR = "terminal_error"
    DETACHED = "detached"


class OccurrenceOperationKind(str, Enum):
    UPDATE = "update"
    CANCEL = "cancel"


class OccurrenceOperationStatus(str, Enum):
    PENDING = "pending"
    TERMINAL = "terminal"


class OccurrenceResolutionKind(str, Enum):
    USE_GOOGLE = "use_google"
    KEEP_PLANNER = "keep_planner"
    DUPLICATED_LOCAL_COPY = "duplicated_local_copy"
    IGNORE = "ignore"


@dataclass(frozen=True)
class GoogleOccurrenceIdentity:
    """Exact Calendar ``originalStartTime`` identity.

    ``kind`` is ``date`` for all-day occurrences and ``datetime`` for timed
    occurrences.  Timed values retain their RFC3339 instant and the explicit
    IANA zone used by the parent series.
    """

    kind: str
    value: str
    timezone_name: Optional[str] = None

    def __post_init__(self) -> None:
        if self.kind not in ("date", "datetime"):
            raise ValueError("original start kind must be date or datetime")
        if self.kind == "date" and self.timezone_name is not None:
            raise ValueError("all-day original start must not have a timezone")
        if self.kind == "datetime" and not self.timezone_name:
            raise ValueError("timed original start requires an IANA timezone")

    @property
    def is_all_day(self) -> bool:
        return self.kind == "date"

    def to_google(self) -> dict[str, str]:
        if self.kind == "date":
            return {"date": self.value}
        return {"dateTime": self.value, "timeZone": str(self.timezone_name)}


@dataclass(frozen=True)
class OccurrenceValidationResult:
    errors: Tuple[str, ...] = field(default_factory=tuple)

    @property
    def ok(self) -> bool:
        return not self.errors

    @property
    def error(self) -> str:
        return self.errors[0] if self.errors else ""


@dataclass(frozen=True)
class OccurrenceMutationProposal:
    series_uid: str
    occurrence_key: str
    operation: OccurrenceOperationKind
    payload: Mapping[str, Any]
    payload_hash: Optional[str] = None
    acknowledged_remote_etag: Optional[str] = None


@dataclass
class OccurrenceCalendarLink:
    series_uid: str
    occurrence_key: str
    series_link_id: int
    link_generation: int
    remote_master_event_id: str
    original_start_kind: str
    original_start_value: str
    original_start_timezone: Optional[str] = None
    remote_instance_event_id: Optional[str] = None
    remote_etag: Optional[str] = None
    remote_updated_at: Optional[datetime] = None
    sync_status: OccurrenceSyncStatus = OccurrenceSyncStatus.LOCAL_ONLY
    last_synced_local_hash: Optional[str] = None
    last_synced_remote_hash: Optional[str] = None
    is_cancelled_remote: bool = False
    conflict_reason: Optional[str] = None
    conflict_snapshot_json: Optional[str] = None
    created_at: datetime = field(default_factory=utc_now)
    updated_at: datetime = field(default_factory=utc_now)
    detached_at: Optional[datetime] = None
    id: Optional[int] = None

    @property
    def identity(self) -> GoogleOccurrenceIdentity:
        return GoogleOccurrenceIdentity(
            self.original_start_kind,
            self.original_start_value,
            self.original_start_timezone,
        )

    @property
    def conflict_snapshot(self) -> Optional[dict[str, Any]]:
        if not self.conflict_snapshot_json:
            return None
        try:
            value = json.loads(self.conflict_snapshot_json)
        except ValueError:
            return None
        return value if isinstance(value, dict) else None


@dataclass
class PendingOccurrenceOperation:
    id: int
    series_uid: str
    occurrence_key: str
    series_link_id: int
    op: OccurrenceOperationKind
    remote_master_event_id: str
    original_start_value: str
    remote_instance_event_id: Optional[str] = None
    acknowledged_remote_etag: Optional[str] = None
    desired_payload_hash: Optional[str] = None
    payload_json: Optional[str] = None
    attempts: int = 0
    last_error: Optional[str] = None
    status: OccurrenceOperationStatus = OccurrenceOperationStatus.PENDING
    created_at: Optional[datetime] = None
    next_try_at: Optional[datetime] = None

    @property
    def payload(self) -> dict[str, Any]:
        if not self.payload_json:
            return {}
        value = json.loads(self.payload_json)
        return value if isinstance(value, dict) else {}


def _parse_timed_occurrence_key(
    schedule: SeriesSchedule, value: str
) -> tuple[date, time]:
    if "@" not in value:
        raise ValueError("timed occurrence_key must contain an IANA timezone")
    wall_text, timezone_name = value.rsplit("@", 1)
    if timezone_name != schedule.timezone_name:
        raise ValueError(
            "occurrence_key timezone does not match the parent series timezone"
        )
    try:
        wall = datetime.fromisoformat(wall_text)
    except ValueError as exc:
        raise ValueError("invalid timed occurrence_key") from exc
    if wall.tzinfo is not None or wall.second or wall.microsecond:
        raise ValueError("timed occurrence_key must be minute-precision wall time")
    expected_time = schedule.local_time
    if expected_time is None:
        raise ValueError("timed series has no local wall-clock time")
    expected_time = expected_time.replace(tzinfo=None)
    if wall.time() != expected_time:
        raise ValueError(
            "occurrence_key wall-clock time does not match the original series slot"
        )
    expected_key = build_occurrence_key(schedule, wall.date())
    if value != expected_key:
        raise ValueError("occurrence_key is not canonical")
    return wall.date(), wall.time()


def local_occurrence_to_google_original_start(
    series: TaskSeries, occurrence_key: str
) -> GoogleOccurrenceIdentity:
    """Map one immutable local slot to exact Google ``originalStartTime``.

    The current materialized Task schedule is intentionally not an input.
    Consequently a moved local exception retains the same remote identity.
    """

    schedule = series.schedule
    key = str(occurrence_key or "")
    if schedule.all_day:
        if "T" in key or "@" in key:
            raise ValueError("all-day occurrence_key must contain only a date")
        try:
            slot_date = date.fromisoformat(key)
        except ValueError as exc:
            raise ValueError("invalid all-day occurrence_key") from exc
        if build_occurrence_key(schedule, slot_date) != key:
            raise ValueError("occurrence_key is not canonical")
        return GoogleOccurrenceIdentity("date", slot_date.isoformat())

    slot_date, slot_time = _parse_timed_occurrence_key(schedule, key)
    resolved = resolve_wall_clock(
        datetime.combine(slot_date, slot_time), schedule.timezone_name
    )
    return GoogleOccurrenceIdentity(
        "datetime",
        resolved.isoformat(),
        schedule.timezone_name,
    )


def _coerce_original_start(original_start: Any) -> GoogleOccurrenceIdentity:
    if isinstance(original_start, GoogleOccurrenceIdentity):
        return original_start
    if isinstance(original_start, Mapping):
        has_date = bool(original_start.get("date"))
        has_datetime = bool(original_start.get("dateTime"))
        if has_date == has_datetime:
            raise ValueError(
                "originalStartTime must contain exactly one of date or dateTime"
            )
        if has_date:
            if original_start.get("timeZone"):
                raise ValueError("all-day originalStartTime must not have a timezone")
            return GoogleOccurrenceIdentity("date", str(original_start["date"]))
        timezone_name = str(original_start.get("timeZone") or "")
        return GoogleOccurrenceIdentity(
            "datetime", str(original_start["dateTime"]), timezone_name
        )
    if isinstance(original_start, date) and not isinstance(original_start, datetime):
        return GoogleOccurrenceIdentity("date", original_start.isoformat())
    if isinstance(original_start, datetime):
        timezone_name = getattr(original_start.tzinfo, "key", None)
        if not timezone_name:
            raise ValueError(
                "timed originalStartTime requires an explicit IANA timezone"
            )
        return GoogleOccurrenceIdentity(
            "datetime", original_start.isoformat(), str(timezone_name)
        )
    raise ValueError("unsupported originalStartTime value")


def google_original_start_to_occurrence_key(
    series: TaskSeries, original_start: Any
) -> str:
    """Map exact Google ``originalStartTime`` back to the immutable local key.

    No matching by the instance's current ``start`` is performed.
    """

    identity = _coerce_original_start(original_start)
    schedule = series.schedule
    if schedule.all_day:
        if identity.kind != "date":
            raise ValueError("timed originalStartTime does not match all-day series")
        try:
            slot_date = date.fromisoformat(identity.value)
        except ValueError as exc:
            raise ValueError("invalid originalStartTime date") from exc
        return build_occurrence_key(schedule, slot_date)

    if identity.kind != "datetime":
        raise ValueError("all-day originalStartTime does not match timed series")
    if identity.timezone_name != schedule.timezone_name:
        raise ValueError(
            "originalStartTime timezone does not match the parent series timezone"
        )
    try:
        remote = datetime.fromisoformat(identity.value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise ValueError("invalid originalStartTime dateTime") from exc
    if remote.tzinfo is None:
        raise ValueError("timed originalStartTime must include an offset")
    try:
        zone = ZoneInfo(schedule.timezone_name)
    except Exception as exc:
        raise ValueError("parent series timezone is invalid") from exc
    remote_local = remote.astimezone(zone)
    key = build_occurrence_key(schedule, remote_local.date())
    expected = local_occurrence_to_google_original_start(series, key)
    expected_dt = datetime.fromisoformat(expected.value)
    if remote.astimezone(expected_dt.tzinfo) != expected_dt:
        raise ValueError(
            "originalStartTime is not an exact slot of the parent series"
        )
    return key


def canonical_occurrence_payload_data(
    payload: Mapping[str, Any],
) -> dict[str, Any]:
    """Return only Planner-owned remote instance fields for hashing."""

    return {
        "summary": str(payload.get("summary") or ""),
        "description": str(payload.get("description") or ""),
        "start": dict(payload.get("start") or {}),
        "end": dict(payload.get("end") or {}),
        "status": str(payload.get("status") or "confirmed"),
    }


def canonical_occurrence_payload_fingerprint(
    payload: Mapping[str, Any],
) -> str:
    value = json.dumps(
        canonical_occurrence_payload_data(payload),
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def planner_occurrence_private_properties(
    series_uid: str,
    occurrence_key: str,
    link_generation: int,
    payload_hash: str,
) -> dict[str, str]:
    return {
        PLANNER_OCCURRENCE_SERIES_UID_PROPERTY: str(series_uid),
        PLANNER_OCCURRENCE_KEY_PROPERTY: str(occurrence_key),
        PLANNER_OCCURRENCE_LINK_GENERATION_PROPERTY: str(int(link_generation)),
        PLANNER_OCCURRENCE_PAYLOAD_HASH_PROPERTY: str(payload_hash),
        PLANNER_OCCURRENCE_SCHEMA_VERSION_PROPERTY:
            PLANNER_OCCURRENCE_SCHEMA_VERSION,
    }


__all__ = [
    "GoogleOccurrenceIdentity",
    "OccurrenceCalendarLink",
    "OccurrenceMutationProposal",
    "OccurrenceOperationKind",
    "OccurrenceOperationStatus",
    "OccurrenceResolutionKind",
    "OccurrenceSyncStatus",
    "OccurrenceValidationResult",
    "PendingOccurrenceOperation",
    "PLANNER_OCCURRENCE_KEY_PROPERTY",
    "PLANNER_OCCURRENCE_LINK_GENERATION_PROPERTY",
    "PLANNER_OCCURRENCE_PAYLOAD_HASH_PROPERTY",
    "PLANNER_OCCURRENCE_SCHEMA_VERSION",
    "PLANNER_OCCURRENCE_SCHEMA_VERSION_PROPERTY",
    "PLANNER_OCCURRENCE_SERIES_UID_PROPERTY",
    "canonical_occurrence_payload_data",
    "canonical_occurrence_payload_fingerprint",
    "google_original_start_to_occurrence_key",
    "local_occurrence_to_google_original_start",
    "planner_occurrence_private_properties",
]
